{% set name = "mpart" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MParT-{{ version }}.tar.gz
  sha256: 096a71b1dcefb1f094971e5e04064b765db19507cd3a1010076970ca2a1fc323

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - {{ compiler('cxx') }}
    - python >=3.7
    - setuptools
    - scikit-build >=0.13
    - cmake >=3.13
    - make
    - pip
  run:
    - python >=3.7

test:
  imports:
    - mpart

about:
  home: https://github.com/MeasureTransport/MParT
  summary: Performance portable implementations of monotone parameterizations and transport maps.
  description: MParT is a library for monotone parameterizations written in c++ with bindings to python, julia, and matlab.  It is designed as a core building block for research and software invovling transport maps and isotonic regression.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://measuretransport.github.io/MParT/
  dev_url: https://github.com/MeasureTransport/MParT

extra:
  recipe-maintainers:
    - mparno
    - dannys4
    - michael-c-brennan
    - bonh
    - rubiop
