{% set name = "mpart" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MParT-{{ version }}.tar.gz
  sha256: 7b11da3f747d44a10e819571def1bbe06551f8519a4e3cf44be6e97f60c7f352

build:
  skip: true  # [win]
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - make
  host:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - setuptools
    - scikit-build >=0.13
    - make
    - python
    - numpy
    - eigen >=3.3.9
    - pybind11
    - pip
    - cereal
    - nlopt
  run:
    - {{ compiler('cxx') }}
    - cmake >=3.13
    - make
    - python
    - {{ pin_compatible('numpy') }}
    - nlopt

test:
  imports:
    - mpart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MeasureTransport/MParT
  summary: Performance portable implementations of monotone parameterizations and transport maps.
  description: MParT is a library for monotone parameterizations written in c++ with bindings to python, julia, and matlab.  It is designed as a core building block for research and software invovling transport maps and isotonic regression.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://measuretransport.github.io/MParT/
  dev_url: https://github.com/MeasureTransport/MParT

extra:
  recipe-maintainers:
    - mparno
    - dannys4
    - michael-c-brennan
    - bonh
    - rubiop
