github:
  branch_name: main
  tooling_branch_name: main
build_platform: {osx_arm64: azure}
test: native_and_emulated
provider: {linux_aarch64: azure, linux_ppc64le: azure}
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
